
package es.jbp.juegos.mus.iu;

import es.jbp.juegos.mus.Jugada;
import es.jbp.juegos.mus.Jugador;
import es.jbp.juegos.mus.Mesa;
import es.shs.comun.utiles.swing.modelos.ModeloLista;

/**
 *
 * @author jorge
 */
public class PanelJugador extends javax.swing.JPanel {

    private Jugador jugador;
    private Mesa mesa;
    /**
     * Creates new form PanelJugador
     */
    public PanelJugador() {
        initComponents();
    }

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

    public Jugador getJugador() {
        return jugador;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    
    
    public void actualizarCartas() {
        
        Jugada jugada = mesa.getJugadaDe(jugador);
        if (jugada == null) {
            System.err.println("El jugador no tene jugada");
            return;
        }
        listaCartas.setModel(new ModeloLista(jugada.getCartas()));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaCartas = new javax.swing.JList<>();
        botonMus = new javax.swing.JButton();
        botonCorto = new javax.swing.JButton();
        botonOrdago = new javax.swing.JButton();
        botonQuiero = new javax.swing.JButton();
        botonNoQuiero = new javax.swing.JButton();
        textMensaje = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botonEnvido = new javax.swing.JButton();
        botonPaso = new javax.swing.JButton();
        botonDescarte = new javax.swing.JButton();

        listaCartas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCartas);

        botonMus.setText("Mus");
        botonMus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMusActionPerformed(evt);
            }
        });

        botonCorto.setText("Corto");
        botonCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCortoActionPerformed(evt);
            }
        });

        botonOrdago.setText("Ordago");
        botonOrdago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdagoActionPerformed(evt);
            }
        });

        botonQuiero.setText("Quiero");
        botonQuiero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuieroActionPerformed(evt);
            }
        });

        botonNoQuiero.setText("No quiero");
        botonNoQuiero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoQuieroActionPerformed(evt);
            }
        });

        textMensaje.setText("jTextField1");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        botonEnvido.setText("Envido");
        botonEnvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnvidoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEnvido);

        botonPaso.setText("Paso");
        botonPaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPasoActionPerformed(evt);
            }
        });
        jPanel1.add(botonPaso);

        botonDescarte.setText("Descarte");
        botonDescarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescarteActionPerformed(evt);
            }
        });
        jPanel1.add(botonDescarte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonMus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCorto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonQuiero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonNoQuiero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(botonOrdago))))
                    .addComponent(textMensaje))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(botonNoQuiero)
                                            .addComponent(botonQuiero))
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botonOrdago)
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonMus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCorto))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addComponent(textMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonMusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMusActionPerformed

    private void botonCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCortoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCortoActionPerformed

    private void botonDescarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDescarteActionPerformed

    private void botonPasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPasoActionPerformed

    private void botonEnvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnvidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnvidoActionPerformed

    private void botonOrdagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOrdagoActionPerformed

    private void botonQuieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuieroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonQuieroActionPerformed

    private void botonNoQuieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoQuieroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNoQuieroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCorto;
    private javax.swing.JButton botonDescarte;
    private javax.swing.JButton botonEnvido;
    private javax.swing.JButton botonMus;
    private javax.swing.JButton botonNoQuiero;
    private javax.swing.JButton botonOrdago;
    private javax.swing.JButton botonPaso;
    private javax.swing.JButton botonQuiero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCartas;
    private javax.swing.JTextField textMensaje;
    // End of variables declaration//GEN-END:variables


}
