package es.jbp.juegos.mus.iu;

import es.jbp.juegos.mus.algoritmo.JugadorAlgoritmo;
import es.jbp.juegos.mus.recursos.RecursoMesa;
import es.shs.comun.utiles.swing.modelos.ModeloLista;
import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author jorge
 */
@Component
public class Ventana extends javax.swing.JFrame {
   
    @Autowired 
    private RecursoMesa recursoMesa;
    
    private final List<PanelJugador> panelesJugadores = new ArrayList();
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();        
    }
    
    public void inicializar() {
        panelJugador1.setNombreJugador("Arturo", 0);
        panelJugador2.setNombreJugador("Bernardo", 1);
        panelJugador3.setNombreJugador("Clemente", 2);
        panelJugador4.setNombreJugador("Dionisio", 3);

        panelJugador1.setJugadorAlgoritmo(new JugadorAlgoritmo(panelJugador1));
        panelJugador2.setJugadorAlgoritmo(new JugadorAlgoritmo(panelJugador2));
        panelJugador4.setJugadorAlgoritmo(new JugadorAlgoritmo(panelJugador4));
        
        
        panelesJugadores.add(panelJugador1);
        panelesJugadores.add(panelJugador2);
        panelesJugadores.add(panelJugador3);
        panelesJugadores.add(panelJugador4);

         recursoMesa.inicializar();
        
        for (PanelJugador panel : panelesJugadores) {            
            panel.setRecursoMesa(recursoMesa);
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelJugador1 = new es.jbp.juegos.mus.iu.PanelJugador();
        jPanel2 = new javax.swing.JPanel();
        panelJugador2 = new es.jbp.juegos.mus.iu.PanelJugador();
        panelMesa = new javax.swing.JPanel();
        panelBotonesMesa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMazo = new javax.swing.JList<>();
        panelJugador4 = new es.jbp.juegos.mus.iu.PanelJugador();
        jPanel3 = new javax.swing.JPanel();
        panelJugador3 = new es.jbp.juegos.mus.iu.PanelJugador();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));
        getContentPane().add(jPanel1);
        getContentPane().add(panelJugador1);
        getContentPane().add(jPanel2);
        getContentPane().add(panelJugador2);

        panelMesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelMesa.setLayout(new javax.swing.BoxLayout(panelMesa, javax.swing.BoxLayout.PAGE_AXIS));

        panelBotonesMesa.setLayout(new javax.swing.BoxLayout(panelBotonesMesa, javax.swing.BoxLayout.LINE_AXIS));
        panelMesa.add(panelBotonesMesa);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 300));

        listMazo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMazo);

        panelMesa.add(jScrollPane1);

        getContentPane().add(panelMesa);
        getContentPane().add(panelJugador4);
        getContentPane().add(jPanel3);
        getContentPane().add(panelJugador3);
        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listMazo;
    private javax.swing.JPanel panelBotonesMesa;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador1;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador2;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador3;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador4;
    private javax.swing.JPanel panelMesa;
    // End of variables declaration//GEN-END:variables

}
