package es.jbp.juegos.mus.iu;

import es.jbp.juegos.mus.Jugador;
import es.jbp.juegos.mus.Mesa;
import es.shs.comun.utiles.swing.modelos.ModeloLista;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jorge
 */
public class Ventana extends javax.swing.JFrame {

    private Mesa mesa = new Mesa();
    private final List<PanelJugador> panelesJugadores = new ArrayList();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        panelJugador1.setJugador(new Jugador("Arturo"));
        panelJugador2.setJugador(new Jugador("Bernardo"));
        panelJugador3.setJugador(new Jugador("Clemente"));
        panelJugador4.setJugador(new Jugador("Dionisio"));
        
        panelesJugadores.add(panelJugador1);
        panelesJugadores.add(panelJugador2);
        panelesJugadores.add(panelJugador3);
        panelesJugadores.add(panelJugador4);
        
        for (PanelJugador panel : panelesJugadores) {
            mesa.agregarJugador(panel.getJugador());
            panel.setMesa(mesa);
        }
               
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJugador1 = new es.jbp.juegos.mus.iu.PanelJugador();
        panelJugador2 = new es.jbp.juegos.mus.iu.PanelJugador();
        panelJugador3 = new es.jbp.juegos.mus.iu.PanelJugador();
        panelJugador4 = new es.jbp.juegos.mus.iu.PanelJugador();
        panelMesa = new javax.swing.JPanel();
        panelBotonesMesa = new javax.swing.JPanel();
        botonBarajar = new javax.swing.JButton();
        botonRepartir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMazo = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(panelJugador1, java.awt.BorderLayout.NORTH);
        getContentPane().add(panelJugador2, java.awt.BorderLayout.WEST);
        getContentPane().add(panelJugador3, java.awt.BorderLayout.SOUTH);
        getContentPane().add(panelJugador4, java.awt.BorderLayout.EAST);

        panelMesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelMesa.setLayout(new javax.swing.BoxLayout(panelMesa, javax.swing.BoxLayout.PAGE_AXIS));

        panelBotonesMesa.setLayout(new javax.swing.BoxLayout(panelBotonesMesa, javax.swing.BoxLayout.LINE_AXIS));

        botonBarajar.setText("Barajar");
        botonBarajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBarajarActionPerformed(evt);
            }
        });
        panelBotonesMesa.add(botonBarajar);

        botonRepartir.setText("Repartir");
        botonRepartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRepartirActionPerformed(evt);
            }
        });
        panelBotonesMesa.add(botonRepartir);

        panelMesa.add(panelBotonesMesa);

        listMazo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMazo);

        panelMesa.add(jScrollPane1);

        getContentPane().add(panelMesa, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBarajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBarajarActionPerformed
        try {
            mesa.inicializar();
            actualizarListaMazo();
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonBarajarActionPerformed

    private void botonRepartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRepartirActionPerformed
        try {
            mesa.repartir();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        for (PanelJugador panel : panelesJugadores) {
            panel.actualizarCartas();
        }
        actualizarListaMazo();
    }//GEN-LAST:event_botonRepartirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBarajar;
    private javax.swing.JButton botonRepartir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listMazo;
    private javax.swing.JPanel panelBotonesMesa;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador1;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador2;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador3;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador4;
    private javax.swing.JPanel panelMesa;
    // End of variables declaration//GEN-END:variables

    private void actualizarListaMazo() {
        ModeloLista modeloMazo = new ModeloLista(mesa.getMazo().getNaipes());
        listMazo.setModel(modeloMazo);
    }
}
