package es.jbp.juegos.mus.iu;

import es.jbp.juegos.mus.Mesa;
import es.shs.comun.utiles.swing.modelos.ModeloLista;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jorge
 */
public class Ventana extends javax.swing.JFrame {

    private Mesa mesa = new Mesa();
    private final List<PanelJugador> panelesJugadores = new ArrayList();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();

        panelJugador1.setNombre("Arturo");
        panelJugador2.setNombre("Bernardo");
        panelJugador3.setNombre("Clemente");
        panelJugador4.setNombre("Dionisio");

        panelesJugadores.add(panelJugador1);
        panelesJugadores.add(panelJugador2);
        panelesJugadores.add(panelJugador3);
        panelesJugadores.add(panelJugador4);

        int i = 0;
        for (PanelJugador panel : panelesJugadores) {
            mesa.agregarJugador(panel, i++);
            panel.setMesa(mesa);
        }
        
        iniciarPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelJugador1 = new es.jbp.juegos.mus.iu.PanelJugador();
        jPanel2 = new javax.swing.JPanel();
        panelJugador2 = new es.jbp.juegos.mus.iu.PanelJugador();
        panelMesa = new javax.swing.JPanel();
        panelBotonesMesa = new javax.swing.JPanel();
        botonIniciarPartida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMazo = new javax.swing.JList<>();
        panelJugador4 = new es.jbp.juegos.mus.iu.PanelJugador();
        jPanel3 = new javax.swing.JPanel();
        panelJugador3 = new es.jbp.juegos.mus.iu.PanelJugador();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));
        getContentPane().add(jPanel1);
        getContentPane().add(panelJugador1);
        getContentPane().add(jPanel2);
        getContentPane().add(panelJugador2);

        panelMesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelMesa.setLayout(new javax.swing.BoxLayout(panelMesa, javax.swing.BoxLayout.PAGE_AXIS));

        panelBotonesMesa.setLayout(new javax.swing.BoxLayout(panelBotonesMesa, javax.swing.BoxLayout.LINE_AXIS));

        botonIniciarPartida.setText("Iniciar");
        botonIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarPartidaActionPerformed(evt);
            }
        });
        panelBotonesMesa.add(botonIniciarPartida);

        panelMesa.add(panelBotonesMesa);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 300));

        listMazo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMazo);

        panelMesa.add(jScrollPane1);

        getContentPane().add(panelMesa);
        getContentPane().add(panelJugador4);
        getContentPane().add(jPanel3);
        getContentPane().add(panelJugador3);
        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarPartidaActionPerformed
        iniciarPartida();

    }//GEN-LAST:event_botonIniciarPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarPartida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listMazo;
    private javax.swing.JPanel panelBotonesMesa;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador1;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador2;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador3;
    private es.jbp.juegos.mus.iu.PanelJugador panelJugador4;
    private javax.swing.JPanel panelMesa;
    // End of variables declaration//GEN-END:variables

    private void actualizarListaMazo() {
        ModeloLista modeloMazo = new ModeloLista(mesa.getMazo().getNaipes());
        listMazo.setModel(modeloMazo);
    }

    private void iniciarPartida() {
        try {            
            mesa.iniciarPartida(0);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        actualizarListaMazo();
    }
}
